/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function showWindow(content: string): void
export declare function windSum(a: number, b: number): number
export declare function winHideTaskBar(types: number): string
export declare function linuxSum(a: number, b: number): number
export declare function linuxHideTaskBar(types: number): string
